title: The Miu Group
description: Stay tuned for more ... 
author: "Evan V. Miu"
email: "evanmiu@caltech.edu"
copyright: "MLab"
theme: minima

base_url: /miugroup.github.io
repository: miugroup/miugroup.github.io

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"
  
# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/people.md
  - _pages/future_research.md
  - _pages/research.md
  - _pages/news.md
  - _pages/contact.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
